/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ns_graph;

import javax.swing.JPanel;

/**
 *
 * @author liuyupeng
 */
public class JTFBody extends javax.swing.JPanel {

    /**
     * Creates new form JTFBody
     */
    public JTFBody() {
        initComponents();
    }
    
    public JPanel getJPanelF(){
        return jPanelF;
    }
    public JPanel getJPanelT(){
        return jPanelT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelT = new javax.swing.JPanel();
        jPanelF = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanelT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelT.setLayout(new java.awt.GridLayout(1, 1));
        add(jPanelT);

        jPanelF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelF.setLayout(new java.awt.GridLayout(1, 1));
        add(jPanelF);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelF;
    private javax.swing.JPanel jPanelT;
    // End of variables declaration//GEN-END:variables
}
