/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ns_graph;

import java.awt.Graphics;
import javax.swing.JLabel;

/**
 *
 * @author liuyupeng
 */
public class JTFHead extends javax.swing.JPanel {

    /**
     * Creates new form JTFHead
     */
    public JTFHead() {
        initComponents();
    }
    
    public JTFHead(String text) {
        initComponents();
        jLabel1.setText(text);
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawLine(0, 0, this.getWidth()/2, this.getHeight());
        g.drawLine(this.getWidth(), 0, this.getWidth()/2, this.getHeight());
        
        g.drawLine(0, (int)(this.getHeight()*0.6), (int)(this.getWidth()*0.05), (int)(this.getHeight()*0.6));
        g.drawLine((int)(this.getWidth()*0.025), (int)(this.getHeight()*0.6), (int)(this.getWidth()*0.025), this.getHeight());
        
        g.drawLine(this.getWidth(), (int)(this.getHeight()*0.6), (int)(this.getWidth()*0.95), (int)(this.getHeight()*0.6));
        g.drawLine((int)(this.getWidth()*0.985), (int)(this.getHeight()*0.8), (int)(this.getWidth()*0.95), (int)(this.getHeight()*0.8));
        g.drawLine((int)(this.getWidth()*0.95), (int)(this.getHeight()*0.6), (int)(this.getWidth()*0.95), this.getHeight());
    }
    
    public JLabel getjLable1(){
        return jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
